apiVersion: v1
kind: Service
metadata:
  name: {{ include "welleating.fullname" . }}
  labels:
    {{- include "welleating.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "welleating.selectorLabels" . | nindent 4 }}
