#!/bin/sh
# WellEating container entrypoint: resolve content, build the site, theme it, serve it.
set -e

SITE_SRC=/opt/welleating/site
HTML=/usr/share/nginx/html
SCRIPTS=/opt/welleating/scripts
SAMPLE=/opt/welleating/sample-content

# ---------- 1. Resolve content ----------
if [ -n "$CONTENT_REPO" ]; then
    echo "Cloning cookbook content from $CONTENT_REPO"
    rm -rf /tmp/content
    git clone --depth 1 ${CONTENT_BRANCH:+--branch "$CONTENT_BRANCH"} "$CONTENT_REPO" /tmp/content
    CONTENT_DIR=/tmp/content
elif [ -d "$CONTENT_DIR/recipes" ]; then
    echo "Using mounted content at $CONTENT_DIR"
else
    echo "No content provided; starting with the sample cookbook."
    echo "Mount your cookbook at /content or set CONTENT_REPO to use your own."
    CONTENT_DIR=$SAMPLE
fi

# ---------- 2. Assemble the site ----------
rm -rf "$HTML"
cp -r "$SITE_SRC" "$HTML"

python3 "$SCRIPTS/build_recipes.py" --source "$CONTENT_DIR/recipes" --output-dir "$HTML"

mkdir -p "$HTML/data"
SHOPPING_SRC="$CONTENT_DIR/pantry/shopping-list.md"
MEALPLAN_SRC="$CONTENT_DIR/meal-plans/current-week.md"
[ -f "$SHOPPING_SRC" ] && cp "$SHOPPING_SRC" "$HTML/data/shopping-list.md"
[ -f "$MEALPLAN_SRC" ] && cp "$MEALPLAN_SRC" "$HTML/data/current-week.md"

# ---------- 3. Runtime config ----------
SHOPPING_URL="null"; [ -f "$HTML/data/shopping-list.md" ] && SHOPPING_URL='"data/shopping-list.md"'
MEALPLAN_URL="null"; [ -f "$HTML/data/current-week.md" ] && MEALPLAN_URL='"data/current-week.md"'
case "$CONTENT_REPO" in
    https://github.com/*) REPO_BLOB="\"${CONTENT_REPO%.git}/blob/${CONTENT_BRANCH:-main}/\"" ;;
    *)                    REPO_BLOB="null" ;;
esac
cat > "$HTML/config.js" << CFG
// Generated by the WellEating container entrypoint.
window.WELLEATING = {
  shopping: $SHOPPING_URL,
  mealplan: $MEALPLAN_URL,
  repoBlob: $REPO_BLOB
};
CFG

# ---------- 4. Theme ----------
theme_css() {
    case "$1" in
        ocean)      echo ":root{--bg:#f0f5f7;--ink:#14303c;--accent:#e0764a;--card:#fdfefe;--muted:#5c7078;--line:#d3dde1;--hero-a:#12303f;--hero-b:#1d4a5b;--hero-accent:#f0b490;--hero-soft:#d3e4ea;--hero-line:#7fa0ad;--deep:#0c2530;--band:#d8e6ea;--band-line:#b8ccd3}" ;;
        terracotta) echo ":root{--bg:#f8f0e9;--ink:#3a2018;--accent:#b3541e;--card:#fffbf7;--muted:#7d6a5e;--line:#e2d5c9;--hero-a:#4a2318;--hero-b:#7a3b24;--hero-accent:#f2b896;--hero-soft:#f3ded2;--hero-line:#b58a72;--deep:#331812;--band:#ecdcc8;--band-line:#d4bfa5}" ;;
        slate)      echo ":root{--bg:#f2f3f2;--ink:#22282c;--accent:#c98a2c;--card:#fcfcfb;--muted:#67707a;--line:#d9dcde;--hero-a:#22282c;--hero-b:#39434b;--hero-accent:#e8b465;--hero-soft:#d7dde2;--hero-line:#8b959e;--deep:#191e22;--band:#e3e0d8;--band-line:#c6c2b6}" ;;
        forest|*)   echo "/* forest: default palette, no overrides */" ;;
    esac
}
{
    echo "/* Theme: ${THEME:-forest} (generated at container start) */"
    theme_css "${THEME:-forest}"
    [ -n "$ACCENT_COLOR" ] && echo ":root{--accent:${ACCENT_COLOR}}"
} > "$HTML/theme.css"
cp "$HTML/theme.css" "$HTML/it/theme.css" 2>/dev/null || true

echo "WellEating ready: theme=${THEME:-forest}, recipes from ${CONTENT_DIR}"

# ---------- 5. Serve ----------
exec nginx -g "daemon off;"
